/* Public reporting-idea library. Titles/source links are references; summaries and prompts are original Woonbi editorial notes. */
(function(){'use strict';
const W=window.Woonbi=window.Woonbi||{};
W.referenceHub=[
 {id:'univ20-home',kind:'잡지 편집',publisher:'대학내일 UNIV20',title:'생활 가까이 붙는 제목과 짧은 데크',source:'https://www.univ20.com/',why:'거대한 담론보다 학생이 실제로 겪는 생활 장면을 제목으로 끌어올리는 방식이 강하다.',try:['우리 학교에서 요즘 가장 자주 들리는 말 10개를 취재한다.','급식·동아리·수행평가처럼 작지만 공감 큰 주제를 1면급으로 다뤄본다.'],tags:['캠퍼스','생활','제목']},
 {id:'univ20-profile',kind:'인물 인터뷰',publisher:'대학내일 UNIV20',title:'표지모델식 TMI 인터뷰',source:'https://www.univ20.com/Magazine/Detail/1743',why:'소개보다 구체적인 생활 질문을 여러 개 던져 인물의 말투와 취향을 살린다.',try:['선생님·학생회·동아리원에게 뻔한 진로 질문 대신 하루 루틴과 실패 경험을 묻는다.','사진 3장과 짧은 문답 8~10개로 구성한다.'],tags:['인터뷰','인물','사진']},
 {id:'yonsei-kimyoungha',kind:'동문 인터뷰',publisher:'연세춘추',title:'90주년 뒷이야기, 김영하 작가의 이야기를 담다',source:'https://chunchu.yonsei.ac.kr/news/articleView.html?idxno=31516',why:'학교의 과거와 현재를 한 인물의 기억으로 연결한다.',try:['포항고 졸업생에게 “내가 기억하는 학교의 한 장면”을 묻는다.','학교 제도 변화보다 당시 학생이 실제로 어떻게 살았는지를 중심에 둔다.'],tags:['동문','학교기억','인터뷰']},
 {id:'yonsei-infographic',kind:'데이터 기사',publisher:'연세춘추',title:'연세인과 주거 인포그래픽',source:'https://chunchu.yonsei.ac.kr/news/articleView.html?idxno=29401',why:'학생 설문을 기사와 그래픽으로 함께 보여주는 전형적인 데이터 저널리즘 사례다.',try:['통학시간·수면·급식 만족·AI 사용·수행평가 부담 중 하나를 100명 이상 설문한다.','표본 수와 조사 기간을 그래프 바로 아래에 적는다.'],tags:['설문','인포그래픽','데이터']},
 {id:'dis-club-policy',kind:'학교 정책 뉴스',publisher:'Daegu International School',title:'Lunch club policies reshape student activities',source:'https://www.dis.sc.kr/community/news',why:'학교 규칙 변화가 학생 생활에 어떤 영향을 주는지 당사자 관점에서 다룬다.',try:['동아리 운영규칙·교실 사용·점심시간 정책 중 최근 바뀐 것을 찾는다.','학생·교사·운영자 최소 3쪽의 목소리를 비교한다.'],tags:['학교정책','동아리','뉴스']},
 {id:'dis-college-fair',kind:'행사 실용 기사',publisher:'Daegu International School',title:'U.S. University Fair provides personalized advice on college applications',source:'https://www.dis.sc.kr/community/news',why:'행사를 “열렸다”로 끝내지 않고 학생이 실제로 얻은 정보와 활용법에 초점을 맞춘다.',try:['특강 후 “그래서 학생이 내일부터 할 수 있는 것 5가지”를 정리한다.','행사 담당자보다 참가 학생의 구체적인 변화부터 묻는다.'],tags:['진로','행사','실용']},
 {id:'dis-counselor-profile',kind:'사람 기사',publisher:'Daegu International School',title:'New Social Emotional Learning Counselor Ms. Zimmerman transforms panic into purpose',source:'https://www.dis.sc.kr/community/news',why:'직책 소개보다 개인의 경험과 학교에서 맡을 역할을 함께 묶는다.',try:['새로 온 교사·행정실 직원·코치·사서 중 한 명을 깊게 인터뷰한다.','“왜 이 일을 시작했나→학생과 어떤 장면에서 만나는가” 순으로 구성한다.'],tags:['사람','프로필','인터뷰']},
 {id:'dis-media',kind:'학생언론 운영',publisher:'Daegu International School',title:'Jets Flyover 학생언론 운영 방식',source:'https://www.dis.sc.kr/arts/media',why:'기사·사진·인터뷰·웹디자인을 수업과 동아리 안에서 분업하고 편집장 역할을 명확히 둔다.',try:['웅비도 취재·사진·교열·디자인 역할을 호마다 바꿔 맡는다.','기사마다 사진 담당과 교열 담당 이름을 기록한다.'],tags:['편집부','운영','학생언론']},
 {id:'nspa-frontpage',kind:'1면 디자인',publisher:'NSPA',title:'2026 Design of the Year — Newspaper Front Page',source:'https://studentpress.org/nspa/2026-design-of-the-year-finalists/',why:'한 호에 모든 기사를 똑같이 보여주지 않고 대표 이슈 하나에 시각적 무게를 집중한다.',try:['한 호의 대표기사 1개·보조기사 2개만 첫 화면 상단에 둔다.','나머지는 섹션 아래로 밀어 기사 위계를 만든다.'],tags:['1면','디자인','위계']},
 {id:'nspa-reading',kind:'교육 이슈',publisher:'NSPA',title:'Reading Regression',source:'https://studentpress.org/nspa/2026-design-of-the-year-finalists/',why:'학생에게 가까운 학습 문제를 자료·인터뷰·디자인으로 풀어낸 고교 언론 주제 사례다.',try:['“우리 학교 학생들은 긴 글을 얼마나 읽나?”를 설문·도서관 대출·인터뷰로 확인한다.'],tags:['교육','탐구','학생생활']},
 {id:'nspa-ai',kind:'AI 교육',publisher:'NSPA',title:'AI in the Classroom / Keeping Up With AI',source:'https://studentpress.org/nspa/spring-2026-best-of-show/',why:'AI를 찬반 논쟁만 하지 않고 실제 교실에서 무엇이 달라졌는지 취재하는 방향을 보여준다.',try:['학생·교사에게 같은 질문을 따로 묻고 답변 차이를 기사 구조로 삼는다.','AI 사용 규칙과 실제 사용 습관의 차이를 사례로 확인한다.'],tags:['AI','수업','취재']},
 {id:'nspa-teaching',kind:'교사 이슈',publisher:'NSPA',title:'The Tolls of Teaching',source:'https://studentpress.org/nspa/spring-2026-best-of-show/',why:'학교 안에서 당연하게 지나치는 교사의 업무와 감정노동을 학생 시선으로 취재할 수 있는 형식이다.',try:['수업 밖에서 교사가 하는 일을 하루 시간표로 기록한다.','교사의 말을 미담으로만 소비하지 말고 제도·업무량과 연결한다.'],tags:['교사','학교생활','심층']},
 {id:'minjok-journal',kind:'학생 연구',publisher:'민족사관고',title:'민족 저널 — 학생 연구를 논문으로 발전시키는 학술지',source:'https://www.minjok.hs.kr/board/bbs39/1942?page=1',why:'학생 탐구를 “활동 후기”가 아니라 질문·방법·결과가 있는 연구 글로 발전시키는 사례다.',try:['R&E 결과를 600자 요약·핵심 그래프·연구 한계로 다시 편집한다.','연구자에게 “다시 한다면 무엇을 바꾸겠나?”를 꼭 묻는다.'],tags:['R&E','연구','학술']},
 {id:'minjok-press',kind:'언론동아리',publisher:'민족사관고',title:'Minjok Herald·Science Newsroom KMLA 등 출판 동아리',source:'https://english.minjok.hs.kr/sub03/sub03_2',why:'일반 학교신문 하나에 모든 분야를 넣기보다 언어·과학·법·문화별 편집 정체성을 만드는 사례다.',try:['웅비 안에 “학교·사람·탐구·지역·사진” 다섯 데스크를 만들고 고정 코너를 운영한다.'],tags:['동아리','전문코너','편집']},
 {id:'kids-localhistory',kind:'지역 답사',publisher:'대구어린이신문',title:'3·1만세운동길 현장 취재',source:'https://kidsnews.daegu.go.kr/',why:'역사 지식을 설명하는 대신 실제 길을 걸으며 장소·사진·현재 풍경을 기사로 엮는다.',try:['포항여중전투·구룡포·철길숲·송도·죽도시장 중 한 곳을 “걸어서 취재”한다.','지도에 4개 지점을 찍고 각 지점마다 사진 1장과 100자 현장 기록을 붙인다.'],tags:['지역사','답사','사진']},
 {id:'pohang-tour',kind:'포항 현장취재',publisher:'포항시 퐝퐝여행',title:'호미곶·구룡포·철길숲·스페이스워크 등 포항 현장 자료',source:'https://pohang.go.kr/phtour/index.do',why:'지역 관광정보를 그대로 소개하는 대신 학생 시선의 검증·비교·역사 취재 출발점으로 쓸 수 있다.',try:['호미곶을 “해맞이 명소”가 아니라 관광객·주민·상인의 서로 다른 시선으로 취재한다.','구룡포는 관광지 설명과 식민지 역사 표기가 어떻게 공존하는지 현장 안내판을 비교한다.'],tags:['포항','탐방','지역']},
 {id:'pohang-college-tour',kind:'타학교 사례',publisher:'포항중앙여고 관련 보도',title:'서울대·고려대 탐방 진로 프로그램',source:'https://v.daum.net/v/6MOyuWTsSF',why:'타 학교의 진로 프로그램을 우리 학교 프로그램과 비교하거나 참가자 후속 변화를 추적할 수 있다.',try:['“대학 탐방이 진로 결정에 실제로 영향을 줬나?”를 참가 전·후 질문으로 검증한다.'],tags:['타학교','진로','비교']},
 {id:'hs-press-ai',kind:'AI와 학생언론',publisher:'High School Press Central',title:'How student newspapers can harness AI in the newsroom',source:'https://www.hspresscentral.com/',why:'AI를 기사 대필이 아니라 자료정리·질문설계·편집 점검에 제한하는 학생언론 관점을 참고할 수 있다.',try:['AI가 만든 문장을 그대로 싣지 않고, 사용한 단계와 사람이 다시 확인한 근거를 기록한다.'],tags:['AI','편집윤리','학생언론']}
];
})();